version: "3.6"
volumes:
  data:
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_PASSWORD=postgrespw"
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  service:
    image: jobservice/service
    build:
      context: ./src
      dockerfile: Dockerfile.service
    ports:
      - "5000:80"
      - "5001:81"
